python/lsst/obs/base/cameraMapper.py
=> add metadata object  lookup for exposure objects

python/lsst/obs/base/cameraMapper.py, tests/testDM-329.py
Adjust to DM-9952 (0-indexed HDUs)
=> DM-9952: 0-indexed HDUs

policy/datasets.yaml
Update datasets.yaml for donut pipeline
=> DM-9567: Create Donut Fit Pipeline

python/lsst/obs/base/cameraMapper.py, python/lsst/obs/base/camera_tests.py
=> DM-12085: Camera geometry incorrect and outdated in obs_test

doc/.gitignore, doc/conf.py, doc/index.rst, doc/lsst.obs.base/index.rst, doc/manifest.yaml, doc/obs_base/index.rst, python/lsst/obs/base/butler_tests.py, python/lsst/obs/base/cameraMapper.py, python/lsst/obs/base/camera_tests.py, python/lsst/obs/base/exposureIdInfo.py, python/lsst/obs/base/makeRawVisitInfo.py, python/lsst/obs/base/mapper_tests.py, python/lsst/obs/base/mapping.py, python/lsst/obs/base/test/compositeMapper.py, python/lsst/obs/base/tests.py, python/lsst/obs/base/yamlCamera.py
Add sphinx support to doc/ and cleanup numpydoc so some docs build.
=> Add sphinx support

policy/datasets.yaml, policy/exposures.yaml
This pull request is being created early to allow comments on the changes. It is not expected to be merged for a while.
=> DM-9615: Add dcrAssembleCoadd config and metadata.

policy/datasets.yaml, policy/exposures.yaml
This replaces pull request #101 , which was created as a branch off of tickets/DM-9615. Now that that branch has been merged, this branch has been rebased to master.
=> DM-14170: Add descriptions of DCR datasets

policy/datasets.yaml
Small additions to datasets.yaml
=> DM-14670: Convert fgcmcal output stars to stack reference catalog format

python/lsst/obs/base/gen3/ingest.py
This is a significant simplification of the Gen3 ingest code, as most of the logic that used to live here has moved to either `daf_butler` or `astro_metadata_translator`.
=> DM-15034: Adapt to dimension refactor in daf_butler.

python/lsst/obs/base/yamlCamera.py
Update yamlCamera camera construction to use Builders().
=> DM-18610: Add fields, limited mutability, and trim/assembly-state tracking to cameraGeom

policy/datasets.yaml
Add configuration for `validate_drp`.
=> DM-21950: Add matchedVisitMetrics_config for persistence.

policy/datasets.yaml, python/lsst/obs/base/_instrument.py, python/lsst/obs/base/gen2to3/convertRepo.py
=> DM-23983: Cannot apply crosstalk in Gen 3 DECam processing

python/lsst/obs/base/exposureAssembler.py, python/lsst/obs/base/formatters/fitsExposure.py, tests/test_butlerFits.py
Filter is going to be a problem.
Depends on lsst/daf_butler#319
=> DM-25447: Add read-only components to gen3 formatter for bbox/xy0/dimensions

python/lsst/obs/base/cli/cmd/commands.py
Reopens #300 on the correct branch.  Requires lsst/daf_butler#377.
=> DM-27680: Add presets command line option for bulk settings command lines

python/lsst/obs/base/_instrument.py, python/lsst/obs/base/filters.py, python/lsst/obs/base/gen2to3/calibRepoConverter.py, python/lsst/obs/base/gen2to3/convertTests.py, python/lsst/obs/base/gen2to3/translators.py, tests/test_filters.py, tests/test_instrument.py
Depends on lsst/daf_butler#378
=> DM-26738: Rename abstract_filter to band

python/lsst/obs/base/cli/cmd/commands.py, python/lsst/obs/base/script/ingestRaws.py, tests/test_cliCmdTestIngest.py
=> DM-26940: Add -j to butler ingest-raws

python/lsst/obs/base/_instrument.py, python/lsst/obs/base/defineVisits.py
Depends on lsst/daf_butler#366
=> DM-26476: Add observation reason to exposure and visit registry

python/lsst/obs/base/gen2to3/calibRepoConverter.py, python/lsst/obs/base/gen2to3/repoConverter.py
@TallJimbo this code seems to work. I'm not asking for a formal review as such since I know it can be cleaned up (by for example moving the new data  structure creation into the earlier loop) but do you see any problems with the general approach?
=> DM-27018: Check for gaps or small overlaps in validity ranges and plug them

python/lsst/obs/base/ingest.py
Now record all failures and summarize problems at the end of ingest.
=> DM-27071: Allow ingest to continue despite failures

python/lsst/obs/base/_instrument.py, python/lsst/obs/base/defineVisits.py, python/lsst/obs/base/ingest.py
Depends on lsst/daf_butler#405 and lsst/astro_metadata_translator#41
=> DM-27321: Add day_obs and seq_num to exposure record

python/lsst/obs/base/gen2to3/convertTests.py
=> DM-25424: Convert Defect to IsrCalib

policy/datasets.yaml
This reverts commit ed67d9df4599aa8e55d111ce12cf5f6ef4e91412, reversing
changes made to 6948e2c5fa213ab94f2d99479e3c2a6defd11c85.
=> DM-23159-revert: Revert "Merge branch 'tickets/DM-23159' into master"

policy/datasets.yaml
One of 4 pull requests for [DM-25304](https://jira.lsstcorp.org/browse/DM-25304), the others being pipe_tasks, daf_butler and obs_subaru.
=> DM-25304: Create task to extract and preprocess bright stars

python/lsst/obs/base/ingest.py
Depends on lsst/daf_butler#512
=> DM-29950: Use repeatable UUID dataset ID for raw ingest

python/lsst/obs/base/_instrument.py
Add support for curated brighter-fatter kernels.
=> DM-30351: Make sure brighter-fatter correction is working on DC2 data for DP0.2

doc/changes/DM-30866.feature.rst, python/lsst/obs/base/defineVisits.py, python/lsst/obs/base/ingest.py, tests/test_ingest.py
=> DM-30866: add support for updating dimension records

python/lsst/obs/base/ingest.py
I needed the ability to ingest skip already-ingested raws for this ticket, and it seemed best to put that into the main ingest task so others could use it, too.  And the flag argument (and test) are already there, from DM-30866 - I just needed to make it more useful.
This also includes the raw-ingest piece of DM-30344.
=> PREOPS-579: Optionally skip previously ingested raws

doc/changes/DM-31079.bugfix.rst, python/lsst/obs/base/cli/cmd/commands.py, python/lsst/obs/base/script/defineVisits.py
=> DM-31079: Let butler define-visits constrain dataIds by collection

python/lsst/obs/base/ingest.py
=> DM-32226: Replace `pipe.base.timeMethod` with `utils.timer`

python/lsst/obs/base/_fitsRawFormatterBase.py, python/lsst/obs/base/cameraMapper.py, python/lsst/obs/base/gen2to3/convertTests.py, python/lsst/obs/base/gen2to3/repoWalker/scanner.py, python/lsst/obs/base/gen2to3/repoWalker/walker.py, python/lsst/obs/base/gen2to3/translators.py, python/lsst/obs/base/makeRawVisitInfo.py, python/lsst/obs/base/makeRawVisitInfoViaObsInfo.py, python/lsst/obs/base/script/defineVisits.py, python/lsst/obs/base/tests.py
=> DM-31801: Use lsst prefix for all loggers

doc/changes/DM-28636.feature.rst, doc/changes/DM-28698.feature.rst, doc/changes/DM-29370.feature.rst, doc/changes/DM-29794.bugfix.rst, doc/changes/DM-29950.feature.rst, doc/changes/DM-30866.feature.rst, doc/changes/DM-31079.bugfix.rst, doc/changes/DM-31903.feature.md, doc/lsst.obs.base/CHANGES.rst
=> DM-32843: v23 release notes

python/lsst/obs/base/gen2to3/convertRepo.py, python/lsst/obs/base/ingest.py, python/lsst/obs/base/ingest_tests.py, tests/test_fitsRawFormatter.py, ups/obs_base.table
=> DM-32817: Switch from ButlerURI to ResourcePath

.pre-commit-config.yaml, python/lsst/obs/base/cameraMapper.py, python/lsst/obs/base/filters.py, python/lsst/obs/base/formatters/fitsExposure.py, python/lsst/obs/base/formatters/packages.py, tests/test_butlerFits.py
=> DM-33403: Update for new location of Packages and new JSON option

python/lsst/obs/base/gen2to3/convertRepo.py, python/lsst/obs/base/gen2to3/repoConverter.py
Missed couple of places where exception type had to be updated for new
types of exceptions.
=> DM-33826: More updates for changes in registry exceptions

doc/changes/DM-33891.feature.rst, python/lsst/obs/base/cli/cmd/commands.py, python/lsst/obs/base/cli/opt/options.py, python/lsst/obs/base/ingest.py, python/lsst/obs/base/script/ingestRaws.py, tests/test_cliCmdTestIngest.py
=> DM-33891 Butler ingest-raws config parameters not accessible from command-line

.github/workflows/formatting.yaml, .github/workflows/lint.yaml, .github/workflows/mypy.yaml, types.txt
=> switch to reusable workflows

doc/changes/DM-35186.feature.rst, python/lsst/obs/base/makeRawVisitInfoViaObsInfo.py, tests/test_makeRawVisitInfoViaObsInfo.py
=> DM-35186: Add focusZ property into makeRawVisitInfoViaObsInfo.

python/lsst/obs/base/ingest_tests.py
=> DM-35670: Add missing lsst.afw.cameraGeom.testUtils for assertDetectorsEqual.

doc/changes/DM-27177.removal.rst, doc/changes/DM-33086.api.rst, doc/changes/DM-33783.removal.rst, doc/changes/DM-33848.feature.rst, doc/changes/DM-33891-hotfix.bugfix.rst, doc/changes/DM-33891.feature.rst, doc/changes/DM-33942.feature.rst, doc/changes/DM-34105.feature.rst, doc/changes/DM-34175.feature.rst, doc/conf.py, doc/lsst.obs.base/CHANGES.rst, pyproject.toml, python/lsst/obs/base/defineVisits.py, python/lsst/obs/base/ingest.py
=> DM-36034: Add v24.0.0 release notes

python/lsst/obs/base/test/dummycam.yaml, python/lsst/obs/base/yamlCamera.py
=> DM-8889: Add detector z-offsets

python/lsst/obs/base/_fitsRawFormatterBase.py, python/lsst/obs/base/formatters/fitsExposure.py, tests/test_butlerFits.py
=> DM-4551: Add test for storage class conversion of afw table to astropy

doc/changes/DM-36597.feature.rst, python/lsst/obs/base/_instrument.py, python/lsst/obs/base/_read_curated_calibs.py
* Add ``transmission_`` curve dataset types to the set of curated calibrations.
* Update the curated calibration code in the ``Instrument`` definition to allow for flexibility in required dimensions.
* Update the read curated calibration code to allow for the same flexibility in dimensions.
=> DM-36597: Add LATISS filter transmission data

tests/test_cliCmdDefineVisits.py
=> DM-31725: update to deal with daf_butler changes

doc/changes/DM-37534.removal.md, python/lsst/obs/base/utils.py
=> DM-37534: Remove deprecated code

.pre-commit-config.yaml, doc/changes/DM-27811.removal.md, doc/changes/DM-35035.feature.rst, doc/changes/DM-35186.feature.rst, doc/changes/DM-35917.api.rst, doc/lsst.obs.base/CHANGES.rst, pyproject.toml, python/lsst/obs/base/exposureAssembler.py, python/lsst/obs/base/instrument_tests.py, tests/test_cliCmdDefineVisits.py, tests/test_cliCmdTestIngest.py, tests/test_cliCmdWriteCuratedCalibrations.py, tests/test_makeRawVisitInfoViaObsInfo.py, types.txt
=> DM-38065: v25 release notes

python/lsst/obs/__init__.py
=> DM-37552: Remove unnecessary import of lsstimport

python/lsst/obs/base/ingest.py
=> DM-37703: Hide unresolved ref warning

python/lsst/obs/base/ingest_tests.py
=> DM-39915: Use new API for getting butler datastore root

python/lsst/obs/base/exposureIdInfo.py
=> DM-40057: shorten deprecation timeline and add ticket TODOs

doc/changes/DM-22465.doc.rst, python/lsst/obs/base/_read_curated_calibs.py
Jenkins run: http://rubin-ci.slac.stanford.edu/job/stack-os-matrix/278/display/redirect
=> DM-22465: Incorrect docstring for read_curated_calibs functions

python/lsst/obs/base/_fitsRawFormatterBase.py, python/lsst/obs/base/_instrument.py, python/lsst/obs/base/defineVisits.py, python/lsst/obs/base/filters.py, python/lsst/obs/base/ingest.py, python/lsst/obs/base/instrument_tests.py, python/lsst/obs/base/script/ingestRaws.py, python/lsst/obs/base/script/writeCuratedCalibrations.py, python/lsst/obs/base/utils.py
=> DM-41235: Update test to use SqlRegistry instead of Registry

python/lsst/obs/base/ingest_tests.py
Depends on lsst/daf_butler#899
=> DM-41365: Use Butler.get_dataset_type API

python/lsst/obs/base/_instrument.py, python/lsst/obs/base/defineVisits.py, python/lsst/obs/base/formatters/fitsExposure.py, python/lsst/obs/base/ingest.py
=> DM-34340: Adapt to daf_butler API changes.

.pre-commit-config.yaml, python/lsst/obs/base/_read_curated_calibs.py, python/lsst/obs/base/yamlCamera.py, setup.cfg
=> Fix radial distortion documentation.

doc/changes/DM-43135.feature.rst, python/lsst/obs/base/cli/cmd/commands.py, python/lsst/obs/base/script/ingestRaws.py, tests/test_cliCmdTestIngest.py
=> DM-43135: Add --update-records to butler ingest-raws command-line

.github/workflows/do_not_merge.yaml, .github/workflows/lint.yaml, .github/workflows/rebase_checker.yaml, .pre-commit-config.yaml, doc/changes/DM-22465.doc.rst, doc/changes/DM-31924.removal.md, doc/changes/DM-36395.feature.rst, doc/changes/DM-36597.feature.rst, doc/changes/DM-36598.bugfix.md, doc/changes/DM-37534.removal.md, doc/changes/DM-37950.feature.rst, doc/changes/DM-38205.feature.md, doc/changes/DM-38779.misc.rst, doc/changes/DM-42636.feature.rst, doc/changes/DM-43135.feature.rst, doc/lsst.obs.base/CHANGES.rst, pyproject.toml, requirements.txt
=> DM-44569: v27 release notes (on release branch)

.github/workflows/rebase_checker.yaml, .pre-commit-config.yaml, doc/changes/DM-22465.doc.rst, doc/changes/DM-31924.removal.md, doc/changes/DM-36395.feature.rst, doc/changes/DM-36597.feature.rst, doc/changes/DM-36598.bugfix.md, doc/changes/DM-37534.removal.md, doc/changes/DM-37950.feature.rst, doc/changes/DM-38205.feature.md, doc/changes/DM-38779.misc.rst, doc/changes/DM-42636.feature.rst, doc/changes/DM-43135.feature.rst, doc/lsst.obs.base/CHANGES.rst, pyproject.toml
=> DM-44569: v27 release notes

python/lsst/obs/base/ingest.py
=> DM-41326: Adapt to removal of DimensionGraph

python/lsst/obs/base/formatters/fitsExposure.py
=> DM-45461: Ensure that the reader object is freed before returning

doc/changes/DM-46297.api.md, doc/lsst.obs.base/CHANGES.rst, requirements.txt
=> DM-47673: Add v28 release notes

doc/changes/DM-47365.feature.rst, python/lsst/obs/base/_instrument.py
=> DM-47365: new manual defects for LSSTComCam

.gitignore, pyproject.toml, python/lsst/obs/base/cli/__init__.py, python/lsst/obs/base/cli/_get_cli_subcommands.py, python/lsst/obs/base/cli/resources.yaml, tests/SConscript, ups/obs_base.table
=> DM-42226: Use entry points for subcommand discovery

python/lsst/obs/base/formatters/fitsGeneric.py, python/lsst/obs/base/utils.py
=> DM-48869: Use the new provenance to dict API

python/lsst/obs/base/_instrument.py, python/lsst/obs/base/makeRawVisitInfoViaObsInfo.py
=> DM-49085: Cast np.float64 to float to fix numpy 2 behavior change

.pre-commit-config.yaml, doc/changes/DM-35396.feature.rst, doc/changes/DM-47365.feature.rst, doc/lsst.obs.base/CHANGES.rst
=> DM-49674: v29 release notes

doc/changes/DM-49845.misc.rst, python/lsst/obs/base/_instrument.py
=> DM-49845: Turn on-sky np floats into python floats for raw ingest

python/lsst/obs/base/defineVisits.py
=> DM-50538: Add logging to DefineVisitsTask.

doc/changes/DM-50661.misc.md, python/lsst/obs/base/cli/cmd/commands.py, python/lsst/obs/base/defineVisits.py, python/lsst/obs/base/ingest_tests.py, python/lsst/obs/base/script/defineVisits.py
=> DM-50661: drop support for old dimension universes in define-visits
